In [3]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 82.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 71.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.8/199.8 KB 23.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 114.3 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125942 sha256=3f0a238dd6a07e495066e077c2f7c52dfb4a849dd7f07665ac75774b333e6b15
  Stored in directory: /root/.cache/pip/wheels/71/67/06/162a3760c40d74dd40bc855d527008d26341c2b0ecf3e8e11f
Successfully built sentence-transformers


In [4]:
from sentence_transformers import SentenceTransformer,util
model=SentenceTransformer('all-MiniLM-L6-V2')

Generate embeddings

In [5]:
sentences=['"Embeddings are a type of representation used in machine learning that can capture the meaning and relationships between words']
embeddings=model.encode(sentences)

for sentence,embedding in zip(sentences,embeddings):
  print('sentence:',sentence)
  print('embeddings:',embedding)

sentence: "Embeddings are a type of representation used in machine learning that can capture the meaning and relationships between words
embeddings: [ 4.96808533e-03 -6.52988479e-02  5.76867955e-03  1.07324747e-02
  3.03837638e-02  8.08755606e-02  1.06561529e-02 -2.84657627e-02
  3.15011255e-02 -7.42102787e-02 -1.92512199e-02  9.21346713e-03
  9.59841907e-02  4.89357933e-02 -5.60037270e-02  9.01461914e-02
  6.70573860e-02  7.76250064e-02 -7.99483284e-02 -4.04657535e-02
  1.75647289e-02 -7.82904960e-03 -3.68420482e-02 -3.61578576e-02
  5.08519746e-02  4.51166555e-03 -4.22441661e-02  7.73208141e-02
  3.50092687e-02  5.87553196e-02  4.05277945e-02  4.88663372e-03
 -6.40412094e-03  5.53339086e-02 -1.34618869e-02  7.16522932e-02
 -3.44193205e-02  6.60396367e-02 -4.41302769e-02 -2.31719073e-02
 -1.51141174e-02  1.14348885e-02 -1.97965316e-02  7.22318813e-02
  1.14024982e-01 -4.97945026e-03 -4.96043116e-02 -3.14461887e-02
 -8.52697194e-02  4.99201640e-02 -1.23247214e-01 -2.19406281e-02
 -6.10

Cosine Similarity

In [6]:
# Compute cosine similarity between all pairs

sentences = ['A woman is reading a book in the park.',
        'A boy is playing soccer with his friends in the backyard.',
        'A group of people are enjoying a picnic near the lake.',
        'A man is walking his dog in the park.',
        'A woman is watering the plants in her garden.',
        'A child is playing with a toy car on the floor.',
        'A man is cleaning his car in the driveway.',
        'A group of friends are hiking in the mountains.',
        'A woman is shopping for groceries at the supermarket.',
        'A man is jogging on the beach.',
        'A group of tourists are taking pictures in front of a famous landmark.'
          ]

embeddings=model.encode(sentences)
#Compute cosine similarity between all pairs
cos_sim= util.cos_sim(embeddings,embeddings)

In [7]:
cos_sim

tensor([[ 1.0000e+00, -1.0287e-02,  1.1940e-01,  3.0116e-01,  3.1447e-01,
         -6.8290e-03,  2.4435e-02,  2.4534e-02,  2.9486e-01,  3.4114e-03,
          1.9877e-02],
        [-1.0287e-02,  1.0000e+00,  1.5851e-01,  1.1315e-01,  1.0113e-01,
          2.2583e-01,  1.4088e-01,  2.6235e-01, -1.1177e-01,  1.1862e-01,
          1.9277e-03],
        [ 1.1940e-01,  1.5851e-01,  1.0000e+00,  9.5945e-02,  9.7617e-02,
         -1.2276e-01, -6.8298e-02,  3.7252e-01, -1.6333e-02,  1.7659e-02,
          2.4279e-01],
        [ 3.0116e-01,  1.1315e-01,  9.5945e-02,  1.0000e+00,  2.0855e-02,
         -1.0063e-01,  2.3433e-01,  1.2783e-01, -8.0989e-03,  2.0025e-01,
         -3.5886e-03],
        [ 3.1447e-01,  1.0113e-01,  9.7617e-02,  2.0855e-02,  1.0000e+00,
         -7.4992e-02,  4.2870e-02, -1.9138e-02,  1.9565e-01,  8.6018e-04,
         -5.3204e-02],
        [-6.8290e-03,  2.2583e-01, -1.2276e-01, -1.0063e-01, -7.4992e-02,
          1.0000e+00,  2.5399e-01, -2.1339e-01,  1.0697e-01, -3.3731e-0

In [8]:
combination=[]
for i in range(len(cos_sim)-1):
  for j in range(i+1,len(cos_sim)):
      combination.append((cos_sim[i][j],i,j))
combination


[(tensor(-0.0103), 0, 1),
 (tensor(0.1194), 0, 2),
 (tensor(0.3012), 0, 3),
 (tensor(0.3145), 0, 4),
 (tensor(-0.0068), 0, 5),
 (tensor(0.0244), 0, 6),
 (tensor(0.0245), 0, 7),
 (tensor(0.2949), 0, 8),
 (tensor(0.0034), 0, 9),
 (tensor(0.0199), 0, 10),
 (tensor(0.1585), 1, 2),
 (tensor(0.1131), 1, 3),
 (tensor(0.1011), 1, 4),
 (tensor(0.2258), 1, 5),
 (tensor(0.1409), 1, 6),
 (tensor(0.2623), 1, 7),
 (tensor(-0.1118), 1, 8),
 (tensor(0.1186), 1, 9),
 (tensor(0.0019), 1, 10),
 (tensor(0.0959), 2, 3),
 (tensor(0.0976), 2, 4),
 (tensor(-0.1228), 2, 5),
 (tensor(-0.0683), 2, 6),
 (tensor(0.3725), 2, 7),
 (tensor(-0.0163), 2, 8),
 (tensor(0.0177), 2, 9),
 (tensor(0.2428), 2, 10),
 (tensor(0.0209), 3, 4),
 (tensor(-0.1006), 3, 5),
 (tensor(0.2343), 3, 6),
 (tensor(0.1278), 3, 7),
 (tensor(-0.0081), 3, 8),
 (tensor(0.2003), 3, 9),
 (tensor(-0.0036), 3, 10),
 (tensor(-0.0750), 4, 5),
 (tensor(0.0429), 4, 6),
 (tensor(-0.0191), 4, 7),
 (tensor(0.1956), 4, 8),
 (tensor(0.0009), 4, 9),
 (tensor(-

In [9]:
#Sort list by the highest cosine similarity score

combination=sorted(combination, key=lambda x:x[0],reverse=True)

In [10]:
print("Top-5 most similar pairs:")

for score,i,j in combination[0:5]:
  print('{} \t {} \t {:.4f}'.format(sentences[i],sentences[j],cos_sim[i][j]))

Top-5 most similar pairs:
A group of people are enjoying a picnic near the lake. 	 A group of friends are hiking in the mountains. 	 0.3725
A group of friends are hiking in the mountains. 	 A group of tourists are taking pictures in front of a famous landmark. 	 0.3221
A woman is reading a book in the park. 	 A woman is watering the plants in her garden. 	 0.3145
A woman is reading a book in the park. 	 A man is walking his dog in the park. 	 0.3012
A woman is reading a book in the park. 	 A woman is shopping for groceries at the supermarket. 	 0.2949


Semantic Search

In [11]:
from sentence_transformers import SentenceTransformer,util
model=SentenceTransformer('clips/mfaq')

/usr/local/lib/python3.9/dist-packages/transformers/configuration_utils.py:379: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


In [15]:
Question= 'How do I reset my password?'

Answer_1= 'To reset your password, go to the login page and click on the "forgot password" link. Follow the instructions to reset your password.'

Answer_2= 'If you\'ve forgotten your password, you can reset it by clicking on the "forgot password" link on the login page.You\'ll be prompted to enter your email address and follow the instructions to reset your password.'

Answer_3 ='If you need to reset your password, go to the login page and click on the "forgot password" link. Enter your email address and follow the instructions to reset your password.'


ques_embedding=model.encode(Question)
ans_embeddings=model.encode([Answer_1,Answer_2,Answer_3])

print(util.semantic_search(ques_embedding,ans_embeddings))

[[{'corpus_id': 0, 'score': 0.7438229918479919}, {'corpus_id': 2, 'score': 0.7425228357315063}, {'corpus_id': 1, 'score': 0.7385133504867554}]]


In [17]:
from transformers import pipeline

In [18]:
qa_model=pipeline('question-answering')

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [19]:
Question= 'What is the difference between a virus and a bacterium?'
Context= 'Viruses are much smaller and require a host cell to replicate, whereas bacteria are single-celled organisms that can reproduce on their own'

qa_model(question=Question,context=Context)


{'score': 0.30014440417289734, 'start': 17, 'end': 24, 'answer': 'smaller'}

Clustering

In [20]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['A woman is reading a book in the park.',
        'A boy is playing soccer with his friends in the backyard.',
        'A group of people are enjoying a picnic near the lake.',
        'A man is walking his dog in the park.',
        'A woman is watering the plants in her garden.',
        'A child is playing with a toy car on the floor.',
        'A man is cleaning his car in the driveway.',
        'A group of friends are hiking in the mountains.',
        'A woman is shopping for groceries at the supermarket.',
        'A man is jogging on the beach.',
        'A group of tourists are taking pictures in front of a famous landmark.'
          ]
totalembeddings=embedder.encode(sentences)

In [21]:
# Normalize the embeddings to unit length
totalembeddings = totalembeddings /  np.linalg.norm(totalembeddings, axis=1, keepdims=True)
     

In [22]:
totalembeddings[0]

array([ 7.71078169e-02, -7.80501813e-02,  7.01533805e-04, -2.68996024e-04,
       -2.41657756e-02,  4.13835235e-02,  2.14598328e-02,  7.72316530e-02,
        9.40469056e-02,  1.11015715e-01, -5.35810776e-02,  8.61700177e-02,
       -2.99277864e-02, -3.65054496e-02,  6.32230705e-03,  3.96724306e-02,
       -1.42791066e-02,  6.67156950e-02,  7.10852668e-02, -4.06533070e-02,
        5.88151366e-02, -1.52831655e-02,  2.65886150e-02,  1.86745264e-02,
       -7.91811198e-02,  6.35479763e-03, -1.07876189e-01, -3.74006631e-04,
       -6.72108009e-02, -1.39954668e-02, -5.11842743e-02,  1.96217988e-02,
       -7.94518180e-03,  1.73214525e-02, -4.78539653e-02,  6.24623522e-02,
        3.37133892e-02, -4.91537862e-02,  3.98670100e-02, -1.35820471e-02,
       -4.16891426e-02,  3.61699465e-04, -1.44007429e-02,  2.40429817e-03,
        7.65431672e-02,  3.12710069e-02,  1.51734222e-02,  3.95584404e-02,
        3.72308132e-04, -7.49989226e-02,  4.50071320e-02,  6.33860826e-02,
        4.86805366e-05, -

In [26]:
clustering_model=KMeans(n_clusters=4)
clustering_model.fit(totalembeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[2 1 1 3 2 0 0 1 2 3 1]


/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [27]:

clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(sentences[sentence_id])
clustered_sentences
     

{2: ['A woman is reading a book in the park.',
  'A woman is watering the plants in her garden.',
  'A woman is shopping for groceries at the supermarket.'],
 1: ['A boy is playing soccer with his friends in the backyard.',
  'A group of people are enjoying a picnic near the lake.',
  'A group of friends are hiking in the mountains.',
  'A group of tourists are taking pictures in front of a famous landmark.'],
 3: ['A man is walking his dog in the park.',
  'A man is jogging on the beach.'],
 0: ['A child is playing with a toy car on the floor.',
  'A man is cleaning his car in the driveway.']}